[package]
name = "monoxus"
version = "0.1.0"
edition = "2024"
description = "Headless Dioxus primitives and shared foundations for accessible, composable component systems."
readme = "README.md"
license = "MIT"
repository = "https://github.com/techton7/monoxus"

[dependencies]
dioxus = { version = "0.7.0", default-features = false, features = ["devtools", "document", "hooks", "html", "mounted", "signals"] }

[dev-dependencies]
dioxus = { version = "0.7.0", default-features = false, features = ["minimal"] }
